# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 609a3de026a078396cc814a9d35f1d782e4bbdcb1f1ebf0bb83493099fa3648e25fbd3db2b00ac9318efa05094bb1d2ba36d2ef9085a63fcbebfcfa9915c048a

test:
  secret_key_base: c09eb29d53223edf5e5fc0a73ef49eb539260a3cc0de16e70452b16a3bb4badf9214339139b5cf4246d67de022820fe629287914be446b535679fd70f20f307b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
